package POJOS;
// Generated 23-ene-2017 14:22:55 by Hibernate Tools 4.3.1



/**
 * Aparatoelectrico generated by hbm2java
 */
public class Aparatoelectrico  implements java.io.Serializable {


     private int codigo;
     private Electrodomestico electrodomestico;
     private String descripcion;

    public Aparatoelectrico() {
    }

    public Aparatoelectrico(int codigo, Electrodomestico electrodomestico, String descripcion) {
       this.codigo = codigo;
       this.electrodomestico = electrodomestico;
       this.descripcion = descripcion;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Electrodomestico getElectrodomestico() {
        return this.electrodomestico;
    }
    
    public void setElectrodomestico(Electrodomestico electrodomestico) {
        this.electrodomestico = electrodomestico;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


