package POJOS;
// Generated 23-ene-2017 14:22:55 by Hibernate Tools 4.3.1



/**
 * Componentes generated by hbm2java
 */
public class Componentes  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String especificaciones;

    public Componentes() {
    }

    public Componentes(int id, String nombre, String especificaciones) {
       this.id = id;
       this.nombre = nombre;
       this.especificaciones = especificaciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEspecificaciones() {
        return this.especificaciones;
    }
    
    public void setEspecificaciones(String especificaciones) {
        this.especificaciones = especificaciones;
    }




}


